{% set name = "librealsense" %}
{% set version = "2.47.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/IntelRealSense/librealsense/archive/v{{ version }}.tar.gz
    sha256: 00767dbc888bc3495aa8f38ec372231bb2c198efb003db3e86af6d2e5458d1bb

build:
  number: 0
  skip: true  # [win]
  run_exports:
    # See https://github.com/IntelRealSense/librealsense/pull/3449
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - libusb


test:
  commands:
    - test -f ${PREFIX}/include/librealsense2/rs.hpp  # [not win]
    - test -f ${PREFIX}/lib/librealsense2.so  # [linux]
    - test -f ${PREFIX}/lib/librealsense2.dylib  # [osx]
    - test -f ${PREFIX}/lib/cmake/realsense2/realsense2Config.cmake  # [not win]
    - if exist %PREFIX%\\Library\\include\\librealsense2\\rs.hpp (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\lib\\realsense2.lib (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\bin\\realsense2.dll (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\lib\cmake\\realsense2\\realsense2Config.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/IntelRealSense/librealsense
  license: Apache-2.0
  license_file: LICENSE
  summary: Cross-platform library for Intel® RealSense™ depth and tracking cameras.

extra:
  recipe-maintainers:
    - traversaro
