{% set name = "librealsense" %}
{% set version = "2.56.5" %}
{% set cuda_enabled = cuda_compiler_version != "None" %}
{% set PY_VER_MAJOR = PY_VER.split('.')[0] %}
{% set PY_VER_MINOR = PY_VER.split('.')[1] %}
{% set build = 2 %}

# Order of priority:
# CUDA 12 (+200)
# CUDA 12 with arm-variant=*=tegra (+150)
# cpu (+0)
# see https://github.com/conda-forge/librealsense-feedstock/issues/41
{% if cuda_compiler_version != "None"  and aarch64 and arm_variant_type == "tegra" %}
{% set build = build + 150 %}
{% else %}
{% if cuda_compiler_version != "None"  %}
{% set build = build + 200 %}
{% endif %}
{% endif %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/IntelRealSense/librealsense/archive/v{{ version }}.tar.gz
    sha256: 58b2029eb7179afc7ea893c25be38a65b42c5b6d27330c8c611bc0e0a4ac5a85
    patches:
      - drop_additional_flags.patch
      - do_not_run_ldconfig_on_install.patch
      - devendor_pybind11.patch
      - fix_pyd_windows_install.patch

build:
  number: {{ build }}
  string: cuda{{ cuda_compiler_version | replace('.', '') }}_py{{ CONDA_PY }}_h{{ PKG_HASH }}_{{ build }}  # [cuda_compiler_version != "None"]
  string: cpu_py{{ CONDA_PY }}_h{{ PKG_HASH }}_{{ build }}                                                 # [cuda_compiler_version == "None"]
  # We do not want to build both (cuda_compiler_version == "None" and arm_variant_type == "sbsa") and  (cuda_compiler_version == "None" and arm_variant_type == "tegra"),
  # as arm_variant_type is ignored for non-CUDA builds, we skip the (cuda_compiler_version == "None" and arm_variant_type == "tegra") case
  skip: true  # [arm_variant_type == "tegra" and cuda_compiler_version != "12.9"]
  ignore_run_exports_from:
    - python
  run_exports:
    # See https://github.com/IntelRealSense/librealsense/pull/3449
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler("cuda") }}  # [cuda_compiler_version != "None"]
    - arm-variant * {{ arm_variant_type }}  # [cuda_compiler_version != "None" and aarch64]
    - cmake <4
    - ninja
    - libudev  # [linux]
  host:
    - python
    - libudev  # [linux]
    - libusb
    - pybind11
    - pybind11-abi
    - nlohmann_json
    - pybind11_json
    - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
    - cuda-cudart-dev  # [cuda_compiler_version != "None"]
  run:
    - __cuda  # [cuda_compiler_version != "None"]

outputs:
  - name: librealsense
    test:
      commands:
        - test -f ${PREFIX}/include/librealsense2/rs.hpp  # [not win]
        - test -f ${PREFIX}/lib/librealsense2.so  # [linux]
        - test -f ${PREFIX}/lib/librealsense2.dylib  # [osx]
        - test -f ${PREFIX}/lib/cmake/realsense2/realsense2Config.cmake  # [not win]
        - if exist %PREFIX%\\Library\\include\\librealsense2\\rs.hpp (exit 0) else (exit 1)  # [win]
        - if exist $PREFIX$\\Library\\lib\\realsense2.lib (exit 0) else (exit 1)  # [win]
        - if exist $PREFIX$\\Library\\bin\\realsense2.dll (exit 0) else (exit 1)  # [win]
        - if exist %PREFIX%\\Library\\lib\cmake\\realsense2\\realsense2Config.cmake (exit 0) else (exit 1)  # [win]

  - name: pyrealsense2
    build:
      string: cuda{{ cuda_compiler_version | replace('.', '') }}_py{{ CONDA_PY }}_h{{ PKG_HASH }}_{{ build }}  # [cuda_compiler_version != "None"]
      string: cpu_py{{ CONDA_PY }}_h{{ PKG_HASH }}_{{ build }}                                                 # [cuda_compiler_version == "None"]
    requirements:
      # There is no build script, but I just want it to think
      # that it needs python and numpy at build time
      host:
        - python
        - numpy
      run:
        - python
        - {{ pin_subpackage('librealsense', exact=True) }}
    test:
      imports:
        - pyrealsense2

about:
  home: https://github.com/IntelRealSense/librealsense
  license: Apache-2.0
  license_file: LICENSE
  summary: Cross-platform library for Intel® RealSense™ depth and tracking cameras.
  description: |
    This feedstock packages the C++ library `librealsense` and the Python library `pyrealsense2`. 
    The packages are built enabling the `FORCE_RSUSB_BACKEND` CMake option, and they are available for all the Linux and macOS platforms supported by conda-forge, including `linux-aarch64` that can be used on Nvidia Jetson boards.
    If your platform is `cuda` capable, a `cuda` enabled package should be installed automatically. If that does not happen, you can force the installation of the `cuda` variant with `conda create -n rsenv librealsense=*=*cuda*` or the 
    command in your preferred conda-based package manager. If for any reason you want to force the installation of librealsense without cuda support, you can do that with `conda create -n rsenv  librealsense=*=*cpu*`.
extra:
  recipe-maintainers:
    - traversaro
