{% set name = "librealsense" %}
{% set version = "2.55.1" %}
{% set cuda_enabled = cuda_compiler_version != "None" %}
{% set build_ext = "cuda" if cuda_enabled else "cpu" %}
{% set PY_VER_MAJOR = PY_VER.split('.')[0] %}
{% set PY_VER_MINOR = PY_VER.split('.')[1] %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/IntelRealSense/librealsense/archive/v{{ version }}.tar.gz
    sha256: 54546d834ff5d8b35d9955319ad2e428f6d9ae4c61b932d1bd716ed81ad135f7
    patches:
      - drop_additional_flags.patch
      - do_not_run_ldconfig_on_install.patch
      - 13079.patch
      - use_cxx17.patch

build:
  number: 1
  string: py{{ PY_VER_MAJOR }}{{ PY_VER_MINOR }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ build_ext }}
  skip: true  # [win]
  skip: true  # [ppc64le and (cuda_compiler_version or "").startswith("12")]
  track_features:           # [cuda_compiler_version != "None"]
    - "librealsense-cuda"   # [cuda_compiler_version != "None"]
  ignore_run_exports_from:
    - python
  run_exports:
    # See https://github.com/IntelRealSense/librealsense/pull/3449
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler("cuda") }}  # [cuda_compiler_version != "None"]
    - cmake <4
    - ninja
    - libudev  # [linux]
  host:
    - python
    - libudev  # [linux]
    - libusb
    - cuda-version {{ cuda_compiler_version }}  # [(cuda_compiler_version or "None") != "None"]
    - cuda-cudart-dev  # [(cuda_compiler_version or "").startswith("12")]
  run:
    - __cuda  # [cuda_compiler_version != "None"]


outputs:
  - name: librealsense
    test:
      commands:
        - test -f ${PREFIX}/include/librealsense2/rs.hpp  # [not win]
        - test -f ${PREFIX}/lib/librealsense2.so  # [linux]
        - test -f ${PREFIX}/lib/librealsense2.dylib  # [osx]
        - test -f ${PREFIX}/lib/cmake/realsense2/realsense2Config.cmake  # [not win]
        - if exist %PREFIX%\\Library\\include\\librealsense2\\rs.hpp (exit 0) else (exit 1)  # [win]
        - if exist $PREFIX$\\Library\\lib\\realsense2.lib (exit 0) else (exit 1)  # [win]
        - if exist $PREFIX$\\Library\\bin\\realsense2.dll (exit 0) else (exit 1)  # [win]
        - if exist %PREFIX%\\Library\\lib\cmake\\realsense2\\realsense2Config.cmake (exit 0) else (exit 1)  # [win]

  - name: pyrealsense2
    build:
      string: py{{ PY_VER_MAJOR }}{{ PY_VER_MINOR }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ build_ext }}
    requirements:
      # There is no build script, but I just want it to think
      # that it needs python and numpy at build time
      host:
        - python
        - numpy
      run:
        - python
        - {{ pin_compatible('numpy') }}
        - {{ pin_subpackage('librealsense', exact=True) }}
    test:
      imports:
        - pyrealsense2

about:
  home: https://github.com/IntelRealSense/librealsense
  license: Apache-2.0
  license_file: LICENSE
  summary: Cross-platform library for Intel® RealSense™ depth and tracking cameras.

extra:
  recipe-maintainers:
    - traversaro
